#!/bin/bash
exec 1>>/var/log/deluge/daemon.log 2>&1

SCRIPTDIR=$(dirname $(readlink -f $0))

$SCRIPTDIR/goplex -mode="deluge" -deluge-torrentid="$1" -deluge-torrentname="$2" -deluge-torrentdir="$3"
echo "Done with GoPlex"
