#!/bin/sh

###########################################
### NZBGET POST-PROCESSING SCRIPT       ###

# Will process nzb with filebot.
#

### NZBGET POST-PROCESSING SCRIPT       ###
###########################################

SCRIPTDIR=$(dirname $(readlink -f $0))

$SCRIPTDIR/goplex -mode="nzbget" -nzbget-status="$NZBPP_TOTALSTATUS" -nzbget-category="$NZBPP_CATEGORY" -nzbget-directory="$NZBPP_DIRECTORY"
